source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel	


  target 'MarvelTests' do
	pod 'SnapKit'
pod 'PagingCollectionViewLayout'
 pod 'Kingfisher', '~> 7.0'
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelUITests' do
    # Pods for testing
  end

end
